### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by Redcom1988** [MyShlongIsLongAT/docker-ncfs-minecraft-server#4]
Server loads normally without any issues regarding NGROK and Cloudflare but upon client connect, it just returns "Connection Refused: No further information" or "java.net.SocketException: Connection reset". No mentions of anyone trying to connect in the server logs.

Docker compose file:
```
version: "3.8"
services:
  minecraft-server:
    image: florianbreuker/docker-ncfs-minecraft-server
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "6.0"
          memory: "6G"  
        reservations:
          cpus: "4.0"
          memory: "2G"
    container_name: minecraft-server
    tty: true
    stdin_open: true
    environment:
      - NGROK_AUTH_TOKEN=[authtoken] # ngrok auth token
      #  If you have a Cloudflare Domain
      - CLOUDFLARE_AUTH_EMAIL=[authemail] # Cloudflare account E-Mail
      - CLOUDFLARE_API_KEY=[apikey] # Cloudflare Global API Key
      - CLOUDFLARE_ZONE_ID=[zoneid] # Cloudflare Zone ID
      - CLOUDFLARE_CNAME_RECORD=minecraft.[domain].com # Cloudflare CNAME Domain
      - CLOUDFLARE_SRV_RECORD=[domain].com # Cloudflare SRV Domain (for your connection)
      - VERSION=1.20.1
      - INIT_MEMORY=6G
      - MAX_MEMORY=6G
      - EULA=true
      - USE_AIKAR_FLAGS=true

    volumes:
      - mcdata:/data:Z

volumes:
  mcdata:
```

Client Logs:
`[Render thread/ERROR] [minecraft/ServerStatusPinger]: Can't ping [serversrvrecord].com: Disconnected`

There weren't any issues yesterday
